# 注意：）複数選択をする場合，スペースを入れるとエラーが発生するので，スペースを入れないようにしてください．
# dataset name: iris, wine, breast_cancer, digits, diabetes, moons, circles, blobs, high_dim (複数選択可)
dataset_name: high_dim

# normalization_method: standard, minmax, robust (複数選択可)       
normalization_method: standard

# encoding_method: 'amplitude', 'phase', 'angle', 'qrac' (複数選択可)    
encoding_method: angle,qrac

print_circuit: False              # True or False
print_eigenvalues: False          # True or False
print_eigenvectors: False         # True or False
print_top_eingenvectors: False    # True or False
print_clasical_data: False        # True or False
