# 注意：）複数選択をする場合，スペースを入れるとエラーが発生するので，スペースを入れないようにしてください．
# dataset name: iris, wine, breast_cancer, digits, diabetes, moons, circles, blobs, high_dim (複数選択可)
dataset_name: iris

# normalization_method: standard, minmax, robust (複数選択可)       
normalization_method: minmax

# encoding_method: 'phase', 'angle', 'qrac' (複数選択可)    
encoding_method: phase

random_seed:
  mode: fixed      # 'fixed' または 'random'
  value: 1         # modeが'fixed'の場合に使用するシード値

print_circuit: False              # True or False
print_eigenvalues: False          # True or False
print_eigenvectors: False         # True or False
print_top_eingenvectors: False    # True or False
print_classical_data: False       # True or False
print_classical_pca: False        # True or False

perform_classical_pca: True      # True or False

num_components: 2                 # 固有値で用いるコンポーネント数（int）

plotting:
  plot_original_data: True
  plot_qpca_results: True
  plot_classical_pca_results: True
  plot_eigenvalues: True
  plot_pca_comparison: True
  save_figures: True
  original_data_fig_path: "original_data.png"
  qpca_results_fig_path: "qpca_results.png"
  classical_pca_results_fig_path: "classical_pca_results.png"
  eigenvalues_fig_path: "eigenvalues.png"
  pca_comparison_eigenvalues_fig_path: "pca_comparison_eigenvalues.png"
  pca_comparison_contribution_fig_path: "pca_comparison_contribution.png"

time_parameter: 1.0
num_ancilla: 8         # ここを 5 か 6 に増やす
repetitions: 1000      # 測定回数も増やす

qpca_mode: block_all      # 'block' or 'block_all' or 'rho_classical'